enum WeirdEnum {
	DOG("woof"), CAT("meow"), FISH("burble");
	String sound;
	WeirdEnum(String s) { sound = s; }
}

class WeirdLoopTest {
	int []testLegal[];
	static WeirdEnum a;
	public static void main(String[] args){
		for (int x = 0; x < 2; x++) ;
		System.out.println(a.DOG.sound);		
		System.out.println(WeirdEnum.DOG.DOG.sound);
		System.out.println(WeirdEnum.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.sound);
		System.out.println(WeirdEnum.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.DOG.FISH.sound);

	}
	
}